/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package competencia;

import javax.swing.text.DefaultCaret;

/**
 *
 * @author danx_
 */
public class Competencia extends javax.swing.JFrame {

    /**
     * Creates new form Competencia
     */
    public Competencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabelCarrera = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        c1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        buttonInicia = new javax.swing.JButton();
        JScrollPane2 = new javax.swing.JScrollPane();
        winner = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Competencia");
        setBackground(new java.awt.Color(0, 0, 255));
        setLocation(new java.awt.Point(400, 100));
        setName("frame"); // NOI18N
        setSize(new java.awt.Dimension(1200, 700));

        jPanel.setBackground(new java.awt.Color(124, 252, 0));
        jPanel.setPreferredSize(new java.awt.Dimension(1200, 700));

        jLabelCarrera.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabelCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCarrera.setText("Carrera");

        c1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        c1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/competencia/caballito.png"))); // NOI18N
        c1.setText("Ed");
        c1.setToolTipText("");
        c1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        c1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        c2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/competencia/caballito.png"))); // NOI18N
        c2.setText("Louise");
        c2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        c2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        c3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/competencia/caballito.png"))); // NOI18N
        c3.setText("Ivan");
        c3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        c3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        c4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/competencia/caballito.png"))); // NOI18N
        c4.setText("Ernest");
        c4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        c4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        txt.setColumns(20);
        txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txt.setRows(5);
        jScrollPane1.setViewportView(txt);

        buttonInicia.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        buttonInicia.setText("Go!");
        buttonInicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIniciaActionPerformed(evt);
            }
        });

        winner.setColumns(20);
        winner.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        winner.setRows(5);
        JScrollPane2.setViewportView(winner);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/competencia/meta.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(buttonInicia)
                .addGap(85, 85, 85)
                .addComponent(JScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(562, 562, 562)
                .addComponent(jLabelCarrera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c1)
                    .addComponent(c3)
                    .addComponent(c2)
                    .addComponent(c4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jLabelCarrera)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(c1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JScrollPane2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonInicia)
                                .addGap(33, 33, 33))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIniciaActionPerformed
        // TODO add your handling code here:
        Caballo cab1 = new Caballo("Ed", c1, txt, winner);
        Caballo cab2 = new Caballo("Louise", c2, txt, winner);
        Caballo cab3 = new Caballo("Ivan", c3, txt, winner);
        Caballo cab4 = new Caballo("Ernest", c4, txt, winner);

        cab1.reset();
        cab2.reset();
        cab3.reset();
        cab4.reset();

        cab1.start();
        cab2.start();
        cab3.start();
        cab4.start();

        //Always update the JScrollPane of the JtextArea
        DefaultCaret caret = (DefaultCaret) txt.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }//GEN-LAST:event_buttonIniciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Competencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Competencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Competencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Competencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Competencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane2;
    private javax.swing.JButton buttonInicia;
    private static javax.swing.JLabel c1;
    private static javax.swing.JLabel c2;
    private static javax.swing.JLabel c3;
    private static javax.swing.JLabel c4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCarrera;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea txt;
    private javax.swing.JTextArea winner;
    // End of variables declaration//GEN-END:variables
}
